### ISSUE TITLE
Name for this repo (the book itself actually)

### ISSUE THREAD

**Issue by tpluscode** [HydraCG/cookbook#2]
That said, we will want to decide on some kind of branding for this as a friendly resource to learn about Hydra.

Once we decide, I'd rename the repo to match the branding.

I will put proposals in comments below for voting

**Comment by tpluscode** [comment]
## Proposal 1

`recipes.hydra-cg.com`

The site would not strictly be a documentation or tutorial. I think `recipes` is appropriate

**Comment by tpluscode** [comment]
## Proposal 2

I own the `hydra.how` domain. I already use it to host docs for Alcaeus client and I think it has potential for nice domain hacks.

> How do I implement Hydra?

`implementing.hydra.how`

**Comment by alien-mcl** [comment]
The `hydra-cg.com` domain fits better - it's the official one, thus I'd expect to have a gitbook under it's wings.

**Comment by alien-mcl** [comment]
##Proposal 3

`cookbook.hydra-cg.com`

Still close to culinary topics :)

**Comment by angelo-v** [comment]
- [x] Proposal 3

**Comment by tpluscode** [comment]
Ok then. Let's first rename this repo to `cookbook` so that it's not named after na implementation detail

Next, we'll work on getting the correct domain for us

**Comment by angelo-v** [comment]
Anything standing in the way? Let's do this. (I do not have the required permissions, perhaps someone could add me to https://github.com/HydraCG)

**Comment by alien-mcl** [comment]
I've just renamed it to `cookbook`.

**Comment by angelo-v** [comment]
What's needed to move to cookbook.hydra-cg.com?

**Comment by tpluscode** [comment]
@lanthaler please add `cookbook CNAME hydra-cookbook.netlify.com.` to DNS records of hydra-cg.com domain

**Comment by lanthaler** [comment]
Done. It's now accessible at https://cookbook.hydra-cg.com
